# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

score_rcpp <- function(prof1, prof2, numLoci, useWildCard, useRareAllele) {
    .Call('_DNAtools_score_rcpp', PACKAGE = 'DNAtools', prof1, prof2, numLoci, useWildCard, useRareAllele)
}

compare <- function(DB, numLoci, bigHit, trace, single, useWildcard, useWildcardEffect, useRallele) {
    .Call('_DNAtools_compare', PACKAGE = 'DNAtools', DB, numLoci, bigHit, trace, single, useWildcard, useWildcardEffect, useRallele)
}

compare_threaded <- function(DB, numLoci, bigHit, trace, single, useWildcard, useWildcardEffect, useRallele) {
    .Call('_DNAtools_compare_threaded', PACKAGE = 'DNAtools', DB, numLoci, bigHit, trace, single, useWildcard, useWildcardEffect, useRallele)
}

#' @export
convolve <- function(x) {
    .Call('_DNAtools_convolve', PACKAGE = 'DNAtools', x)
}

#' @export
Pnm_locus <- function(m, theta, alleleProbs) {
    .Call('_DNAtools_Pnm_locus', PACKAGE = 'DNAtools', m, theta, alleleProbs)
}

Pnm_all_cpp <- function(numContrib, theta, loci) {
    .Call('_DNAtools_Pnm_all_cpp', PACKAGE = 'DNAtools', numContrib, theta, loci)
}

generateCompositions <- function(numContributors) {
    .Call('_DNAtools_generateCompositions', PACKAGE = 'DNAtools', numContributors)
}

Prob <- function(vstrCombs, q, R, r, t) {
    .Call('_DNAtools_Prob', PACKAGE = 'DNAtools', vstrCombs, q, R, r, t)
}

